sonar.projectKey=FarwBr_financaspro
sonar.organization=farwbr
sonar.projectName=FinancasPro
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/test_app.py,**/__pycache__/**,**/venv/**,**/migrations/**
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8