# sonar-project.properties
# Substitua os valores abaixo pelos do seu SonarCloud

sonar.projectKey=SEU_USUARIO_financaspro
sonar.organization=SEU_USUARIO

sonar.projectName=FinancasPro
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/test_app.py,**/__pycache__/**,**/venv/**,**/migrations/**,**/node_modules/**

sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
