name: CD — Deploy Produção

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    name: 🚀 Deploy Produção
    runs-on: self-hosted

    steps:
      - name: Deploy Produção
        run: |
          cd /home/univates/financaspro
          git pull origin main
          sudo docker compose build
          sudo docker compose up -d
          echo "Deploy produção concluído!"
          sudo docker ps | grep financas